# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kyle Kuberskis Website
tagline:          'A Personal Page for Projects'
description:      'This site includes an "About me", general projects throughout my journey in Data Science, and more!'
url:              https://kylekuberski.github.io/
baseurl:          /

author:
  name:           'Kyle Kuberski'
  url:            https://www.linkedin.com/in/kyle-kuberski/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/KyleKuberski
